-- REWARD_POINTS 생성 후 최초 1회 기본 점수를 채운다.
-- 이후 월별 관광지수 작업이 지역 난이도를 반영한 점수로 갱신한다.
UPDATE MISSIONS
SET REWARD_POINTS = CASE MISSION_CATEGORY
    WHEN '식당방문' THEN 100
    WHEN '관광지방문' THEN 120
    WHEN '체험' THEN 150
    WHEN '등산' THEN 170
    WHEN '경기관람' THEN 200
    ELSE 0
END
WHERE REWARD_POINTS IS NULL;

ALTER TABLE MISSIONS MODIFY (REWARD_POINTS DEFAULT 0 NOT NULL);

COMMIT;
