-- Apply before deploying coordinate-free mission verification (Oracle).
CREATE TABLE LOCATION_CHALLENGES (
    USER_CODE VARCHAR2(50) PRIMARY KEY REFERENCES APP_USERS(USER_CODE),
    CHALLENGE_ID VARCHAR2(64) NOT NULL,
    MISSION_ID NUMBER NOT NULL REFERENCES MISSIONS(MISSION_ID),
    POLICY_HASH VARCHAR2(64) NOT NULL,
    ISSUED_AT TIMESTAMP NOT NULL,
    EXPIRES_AT TIMESTAMP NOT NULL,
    CONSUMED NUMBER(1) DEFAULT 0 NOT NULL
);
